version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=${JAEGER_ZIPKIN_PORT:-9411}
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "${JAEGER_UI_PORT:-16686}:16686"          # UI port
      - "${JAEGER_COLLECTOR_PORT:-14250}:14250"   # Model used by jaeger-agent to send spans to collector
      - "${JAEGER_COLLECTOR_HTTP:-14268}:14268"   # Can accept spans directly from clients in jaeger.thrift format
      - "${JAEGER_COLLECTOR_OTLP:-4317}:4317"     # OTLP gRPC
      - "${JAEGER_COLLECTOR_OTLP_HTTP:-4318}:4318" # OTLP HTTP
      - "${JAEGER_AGENT_PORT:-6831}:6831/udp"     # Accept jaeger.thrift in compact Thrift protocol used by most jaeger clients
      - "${JAEGER_ZIPKIN_PORT:-9411}:9411"        # Zipkin compatible endpoint
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge 